In [1]:
#import necessary libraries
import pandas as pd
import numpy as np
import os
from PIL import Image

In [2]:
def load_data(data_dir):
    images = []
    labels = []
    digits_folders = [str(i) for i in range(10)]
    
    for label in digits_folders:
        folder_path = os.path.join(data_dir, label)
        for file in os.listdir(folder_path):
            if file.endswith('.png'):
                img_path = os.path.join(folder_path, file)
                img = Image.open(img_path).convert('L')  
                img = img.resize((50, 50)) 
                img_array = np.array(img)
                images.append(img_array)
                labels.append(int(label))
    
    images = np.array(images)
    labels = np.array(labels)
    
    return images, labels

data_dir = r'C:\Users\HP PC\Downloads\Gesture Image Pre-Processed Data Output'
images, labels = load_data(data_dir)

In [3]:
images

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [4]:
labels

array([0, 0, 0, ..., 9, 9, 9])

In [5]:
print(f"shape of images is {images.shape} and shape of labels is {labels.shape}")

shape of images is (15000, 50, 50) and shape of labels is (15000,)


In [6]:
X=images

In [7]:
#reshaping the input image to approprite dimensions as well as appropraite scaling for use of conventional neutral network
X=X.reshape(-1,2500)
X=X.astype("float32")/255

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
#splitting of train_test data(random shuffling)
x_train,x_test,y_train,y_test=train_test_split(X,labels,test_size=0.2)

In [10]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [11]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import l2
from tensorflow.keras.layers import Dense, Flatten, BatchNormalization

In [16]:
#construction and training of a simple neural network(7 layers)
model = tf.keras.Sequential([
    Dense(512, activation='relu', input_shape=(2500,), kernel_regularizer=tf.keras.regularizers.l2(0.001)),
    BatchNormalization(),
    Dense(256, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
     BatchNormalization(),
    Dense(128, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
     BatchNormalization(),
    Dense(64, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
     BatchNormalization(),
    Dense(32,activation="relu",kernel_regularizer=tf.keras.regularizers.l2(0.001)),
     BatchNormalization(),
    Dense(10,activation="linear")  
])

#softmax loss with Adam optimization
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.summary()




Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_14 (Dense)                     │ (None, 512)                 │       1,280,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_12               │ (None, 512)                 │           2,048 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_15 (Dense)                     │ (None, 256)                 │         131,328 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_13               │ (None, 256)                 │           1,024 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_16 (Dense)                     │ (None, 128)                 │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_14               │ (None, 128)                 │             512 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_17 (Dense)                     │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_15               │ (None, 64)                  │             256 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_18 (Dense)                     │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_16               │ (None, 32)                  │             128 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_19 (Dense)                     │ (None, 10)                  │             330 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,459,370 (5.57 MB)

 Trainable params: 1,457,386 (5.56 MB)

 Non-trainable params: 1,984 (7.75 KB)

In [18]:
history = model.fit(x_train, y_train, epochs=10, batch_size=100, validation_split=0.2)
test_loss,test_acc=model.evaluate(x_test,y_test)



print(f"Test accuracy: {test_acc:.4f}")

Epoch 1/10
96/96 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - accuracy: 0.9948 - loss: 0.2149 - val_accuracy: 0.9887 - val_loss: 0.1974
Epoch 2/10
96/96 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.9994 - loss: 0.1539 - val_accuracy: 0.9658 - val_loss: 0.2163
Epoch 3/10
96/96 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9941 - loss: 0.1467 - val_accuracy: 0.8779 - val_loss: 0.4484
Epoch 4/10
96/96 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9917 - loss: 0.1655 - val_accuracy: 0.9987 - val_loss: 0.1392
Epoch 5/10
96/96 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - accuracy: 0.9996 - loss: 0.1205 - val_accuracy: 0.9833 - val_loss: 0.1484
Epoch 6/10
96/96 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 1.0000 - loss: 0.0854 - val_accuracy: 0.9808 - val_loss: 0.1490
Epoch 7/10
96/96 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - accuracy: 0.9854 - loss: 0.1404 - val_accuracy: 0.8225 - val_loss: 0.9241
Epoch 8/10
96/96 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.9940 - loss: 0.1351 - val_accuracy: 0.9979 - v

In [19]:
help1=tf.nn.softmax(model.predict(x_test))
predicted_classes = tf.argmax(help1, axis=1).numpy().flatten()
comparison_df = pd.DataFrame({'Actual': y_test, 'Predicted': predicted_classes})
comparison_df

94/94 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step


Actual  Predicted
0          2          2
1          6          6
2          9          9
3          3          3
4          8          8
...      ...        ...
2995       9          9
2996       1          1
2997       8          8
2998       9          9
2999       0          0

[3000 rows x 2 columns]

In [49]:
#Even by using a simpler model,able to attain test_accuracy of a little more than 98 percent 
#Number of parameters around 3 million

In [20]:
x_train=x_train.reshape(-1,50,50,1)
x_test=x_test.reshape(-1,50,50,1)

In [21]:
#Now using convulational layer and functional API
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Flatten, Dense,Dropout
from tensorflow.keras.models import Model
input_shape = (50, 50, 1)  
inputs = Input(shape=input_shape)
x = Conv2D(64, (3, 3), activation='relu', padding='same')(inputs)
x = MaxPooling2D((2, 2))(x)
x = Conv2D(32, (3, 3), activation='relu', padding='same')(x)
x = MaxPooling2D((2, 2))(x)
x=Conv2D(16, (3,3), activation="relu", padding='same')(x)





x=MaxPooling2D((8,8))(x)
x=Conv2D(filters=8, kernel_size=(2,2), activation="relu", padding='same')(x)





x=MaxPooling2D(pool_size=(4,4), strides=(4,4), padding='same')(x)




x = Flatten()(x)

# Dense layer with 1 unit for output & 'sigmoid' activation
outputs=tf.keras.layers.Dense(units=10, activation='softmax')(x)


In [22]:
my_model=Model(inputs=inputs,outputs=outputs)

In [23]:
my_model.compile(optimizer="Adam",loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])
my_model.summary()

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_3 (InputLayer)           │ (None, 50, 50, 1)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d (Conv2D)                      │ (None, 50, 50, 64)          │             640 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 25, 25, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 25, 25, 32)          │          18,464 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 12, 12, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 12, 12, 16)          │           4,624 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 1, 1, 16)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 1, 1, 8)             │             520 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 1, 1, 8)             │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 8)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_20 (Dense)                     │ (None, 10)                  │              90 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 24,338 (95.07 KB)

 Trainable params: 24,338 (95.07 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
my_model.fit(x_train,y_train,epochs=20,batch_size=150,validation_split=0.2)
test_loss, test_acc = my_model.evaluate(x_test,y_test)
print(f"Test accuracy: {test_acc:.4f}")

Epoch 1/20


C:\Users\HP PC\AppData\Roaming\Python\Python312\site-packages\keras\src\backend\tensorflow\nn.py:609: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


64/64 ━━━━━━━━━━━━━━━━━━━━ 21s 250ms/step - accuracy: 0.1330 - loss: 2.2585 - val_accuracy: 0.2708 - val_loss: 1.9169
Epoch 2/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 16s 255ms/step - accuracy: 0.2954 - loss: 1.8250 - val_accuracy: 0.4854 - val_loss: 1.4958
Epoch 3/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 16s 246ms/step - accuracy: 0.4949 - loss: 1.4151 - val_accuracy: 0.5958 - val_loss: 1.1319
Epoch 4/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 15s 239ms/step - accuracy: 0.6629 - loss: 1.0473 - val_accuracy: 0.7267 - val_loss: 0.8456
Epoch 5/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 15s 240ms/step - accuracy: 0.7763 - loss: 0.7471 - val_accuracy: 0.8425 - val_loss: 0.5985
Epoch 6/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 16s 247ms/step - accuracy: 0.8651 - loss: 0.5499 - val_accuracy: 0.8783 - val_loss: 0.4874
Epoch 7/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 16s 244ms/step - accuracy: 0.8738 - loss: 0.4852 - val_accuracy: 0.8850 - val_loss: 0.4413
Epoch 8/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 15s 238ms/step - accuracy: 0.8806 - loss: 0.4486 - val_accuracy: 0.886

In [25]:
help1=tf.nn.softmax(my_model.predict(x_test))
predicted_classes = tf.argmax(help1, axis=1).numpy().flatten()

94/94 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step


In [26]:
comparative_df = pd.DataFrame({'actual': y_test, 'predictions': predicted_classes})

In [27]:
comparative_df

actual  predictions
0          2            2
1          6            6
2          9            9
3          3            3
4          8            8
...      ...          ...
2995       9            9
2996       1            1
2997       8            8
2998       9            9
2999       0            0

[3000 rows x 2 columns]

In [ ]:
#The convolutational model produces an accuracy of 99.77 percent on test set with only 24,000 parameters..making it far better computationally 
#than its simple counterpart